name: 'Generate semantic version'
description: 'Generate new version on release type name'
inputs:
  bump:
    description: 'The type of semantic version increment to make (one of major, premajor, minor, preminor, patch, prepatch, or prerelease)'
    required: true
  github_token:
    description: 'Token to use to push to the repo. Pass in using `secrets.GITHUB_TOKEN`.'
    required: true
  preid:
    description: 'Identifier to be used to prefix premajor, preminor, prepatch or prerelease version increments.'
    required: false
    default: ""
outputs:
  version:
    description: 'The new semantic version that was calculated.'
  version_optimistic:
    description: 'The major and minor components of the semantic version that was calculated.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'  
  color: 'blue'
